import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider,hasLocale } from 'next-intl';
import { getMessages } from 'next-intl/server';
import { notFound } from 'next/navigation';
import { routing } from '@/shared/i18n/routing';
import { LocaleType } from '@/shared/types/index.type';
import { ThemeProvider } from 'next-themes';
import Header from '@/widgets/Header/Header';
import Footer from '@/widgets/Footer/Footer';
import SocialLinks from '@/features/SocialLinks/SocialLinks';



const plexMono = IBM_Plex_Mono({
  weight: ['400'],
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: { locale: LocaleType };
}>) {

  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
    const messages = await getMessages();

    return (
      <html lang={locale} suppressHydrationWarning>
        <body className={` ${plexMono.className} antialiased min-h-screen dark:bg-primary-dark  bg-primary-light`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
            <NextIntlClientProvider messages={messages}>
              <Header/>
              <SocialLinks position="side" />
              <main>

              {children}
              </main>
              <Footer/>
            </NextIntlClientProvider>
          </ThemeProvider>
        </body>
      </html>
    );
  
}